### ISSUE TITLE
Why is the source code so messy?

### ISSUE THREAD

**Issue by Legendary-Candice-Joe** [FrazeRIP/FNF-LateNightCityTales#1]
### What is your question?

Why is it so messy?

For example, why is the everything in the mods folder not hard coded? Or at the very least copied into the "example_mods" folder which will copy everything into the mods folder anyway?

Why is a glow effect created every single frame? Rather than just using an asset? This causing the game to slow down to a crawl.
Also back to the mods folder thing, I assume this was compiled in debug mode. This on its own will take a bit of performance, compile the game without a debug flag geez.

Also why 4 separate cameras for the note effects, if it was an asset it would have been easier to use a colourswap shader on top of that.

**Comment by FrazeRIP** [comment]
You're right, when I was making the mod I wasn't very experienced with Haxe, I kinda just cut corners to everything and use the easiest approach/method that works. Right now I realized a lot of things could be done in a more straightforward way but I don't have the energy to redo all of them. This is the first mod I have been working on as a programmer, I still have a lot of things to learn. Hopely I won't make the same mistake on the next project.

**Comment by FrazeRIP** [comment]
I prefer to use Lua cuz my pc went slow every time I compile the game while in Lua I can just restart the level and see the result. The camera glow needs 4 colors for each type of note and it needs to be dynamic breathing. Simply applying shaders to that camera works but I cannot find a way to make it breathe so the current implementation is the shortcut for that (I don't even know about shaders while I made that). Maybe there are more resources to learn to code right now but way back then there is a limited amount of them or maybe I just haven't found them. I'm not good enough, and I saw making this mod as my opportunity to learn how to code. Thank you for pointing out all the improvements, I will definitely try them out in my next project.

**Comment by Legendary-Candice-Joe** [comment]
That makes sense.
I have made a few optimizations, such as removing the glow effect. Which instantly made the game playable.
I would rather re-write most of everything here than fixing it.

Oh well, its fine. But I also don't think its worth my time to fix this.

**Comment by Legendary-Candice-Joe** [comment]
<del>Also with the glow effect, It might be more complicated but I you could probably render the glow effects as bitmap data, and put them onto camHUD. </del> Nvm, just a single glow effect (even without a new one being created every frame) is enough to tank this game's FPS. 

And with Lua, you can always use the assets folder, they dont need to be in mods.

Also the blur shader can be its own variable, so you can control the blurX and blurY without creating a new one every frame.

**Comment by FrazeRIP** [comment]
Thank you for the suggestions. I will definitely try those myself and see how it works. It is good to know that Haxe is a very powerful programming language and there are decent programmers like you to support the community. Again really appreciate your effort and hope you have a good day!

**Comment by Legendary-Candice-Joe** [comment]
Thx and have a blessed day.
