### ISSUE TITLE
EXTREMELY Sorry for the new issue.

### ISSUE THREAD

**Issue by Legendary-Candice-Joe** [FrazeRIP/FNF-LateNightCityTales#2]
### What is your question?

Quick question (before I close this). Why was the source code hidden for so long? There's no sensitive information or much reason not to. I just wanted to know why this wasn't already open sourced earlier. Especially since you technically supposed to since this was under the official fnf github.
![image](https://user-images.githubusercontent.com/105545224/202068372-5122d7e0-39c9-4846-b6ae-040a199b3984.png)
After a response I'll probably stop making new issues.

**Comment by FrazeRIP** [comment]
The source code is hidden cuz we want to prevent potential leaks in future updates. I also noticed that a lot of my stuff is using really bad programming approaches that should not be used as samples. After the mod is canceled there is no reason to keep it a secret and I'm too tired to fix all the programming issues so I decided to open source it now as a signal of the end of the project.

**Comment by Legendary-Candice-Joe** [comment]
Alr thx man. I'll leave this repo alone now.

Thank you and have a blessed day.
